services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "1245:5432"
    environment:
      POSTGRES_DB: ticketing
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --notify-keyspace-events Ex
    container_name: ticketing-redis
    ports:
      - "2356:6379"
    restart: always

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketing-spring
    depends_on:
      - postgres
      - redis
    ports:
      - "8147:8147"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: ticketing-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - spring
    networks:
      - ticketing-network

  grafana:
    image: grafana/grafana
    container_name: ticketing-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - ticketing-network

volumes:
  postgres_data:
  grafana-data:

networks:
  ticketing-network:
    driver: bridge