version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "1245:5432"
    environment:
      POSTGRES_DB: ticketing
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ticketing-redis
    ports:
      - "2356:6379"
    restart: always

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketing-spring
    depends_on:
      - postgres
      - redis
    ports:
      - "8147:8147"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always

volumes:
  postgres_data: