spring:
  profiles:
    active: local

  application:
    name: ticketing-server

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8147

logging:
  level:
    root: info

security:
  jwt:
    secret: "ticketing-server-jwt-secret-key-ticketing-server-jwt-secret-key"
    access-exp-min: 60