spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://postgres:1245/ticketing # docker 내부 통신이면 postgres
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # 운영에서는 스키마 검증만
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false

logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: off
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: error # SQL 오류 로그 핵심