spring:
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 5000

  application:
    name: ticketing-server

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8147
  tomcat:
    threads:
      max: 300
      min-spare: 50
    accept-count: 500
    max-connections: 2000

logging:
  level:
    root: info

security:
  jwt:
    secret: "ticketing-server-jwt-secret-key-ticketing-server-jwt-secret-key"
    access-exp-min: 60

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ticketing-server

kind: Application