global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "ticketing-spring"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ticketing-spring:8147"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]